### ISSUE TITLE
Polyfill has a lot of dead code...

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/proposal-promise-finally#19]
[None of this can be executed.](https://github.com/tc39/proposal-promise-finally/blob/master/polyfill.js#L11-L25)

**Comment by ljharb** [comment]
Thanks - polyfill code in proposal repos isn't that important; the actual polyfill is https://www.npmjs.com/package/promise.prototype.finally / https://github.com/es-shims/Promise.prototype.finally/blob/master/implementation.js which gets its speciesConstructor implementation from https://github.com/ljharb/es-abstract/blob/master/es6.js#L237-L255.

I'll put up a fix shortly.
