### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GrosSacASac** [tc39/proposal-promise-finally#28]
What are the benefits over a functional inclusion at the end of both resolve and reject ?

```
const myFinally = function () {
  // do clean up 
};

work("test/sort", [1,2,3,-8,-5,2,3,45,5]).then(function (result) {
    console.log(result);
    myFinally();
    // included here
}).catch(function (reason) {
    console.log("Error:", reason);
    myFinally();
    // included here
});
```

**Comment by ljharb** [comment]
In your example, your `.catch` doesn't re-throw `reason`, and your `.then` doesn't re-return `result` - which means that the resulting promise ends up resolved to `undefined`.

If instead, you did: `work(blah).finally(myFinally)`, then the resulting promise would continue to be resolved with `result` or rejected with `reason`, without any additional work on your end.
