### ISSUE TITLE
Editorial: weird extra spaces in the output

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-promise-finally#30]
E.g. double-spaces between each ?/! and the call, or in `NewPromiseCapability( %Promise%)`. Probably fixable by updating ecmarkup.

**Comment by ljharb** [comment]
Turns out it's a bug in ecmarkup (not fixed in latest), so I removed the single space in the input to work around for now.

(ping @bterlson)

**Comment by domenic** [comment]
That's bizarre; are you sure you're on latest? None of my specs have this problem.

**Comment by ljharb** [comment]
I'm sure; I bumped the versions and ran `npm install`.

**Comment by domenic** [comment]
This appears to be caused by the mysterious js-beautify package.

**Comment by ljharb** [comment]
ah yes, i believe that was [your recommendation](https://github.com/bterlson/ecmarkup/issues/30#issuecomment-129036099) when ecmarkup removed some formatting of the output iirc :-p
