### ISSUE TITLE
Editorial: use backticks for strings

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-promise-finally#31]
In particular in `Return ?  Invoke(promise, "then", « thenFinally, catchFinally »)`.

**Comment by ljharb** [comment]
The spec commonly uses stars inline in algorithm steps so that the literal string values are bolded, but I also see backticked strings, but these seem to only appear in prose.

**Comment by domenic** [comment]
There were recently some inconsistencies introduced by accidentally using stars, but backticks are what's intended. There was a recent discussion about this in one of the repos.

**Comment by ljharb** [comment]
Thanks, could you link me to that discussion?

**Comment by domenic** [comment]
Sorry, I can't find it right now; you can either take my word or ask @bterlson to make an editor call or find it yourself.

**Comment by bterlson** [comment]
I'll try to find the issue when I'm at a computer but the gist is backtick for now, though may change esp. depending on editorial changes in support of number type reform (and fwiw my intent was to use stars for strings but backticks matched the old spec's presentation).
