### ISSUE TITLE
TYPO in CatchFinally: we need use reason instead of value

### ISSUE THREAD

**Issue by gskachkov** [tc39/proposal-promise-finally#35]
I think there is  typo in CatchFinally function (https://tc39.github.io/proposal-promise-finally/#sec-catchfinallyfunction) we need to use _reason_ name of input argument  instead of _value_ because we rethrow it with name _reason_ in 1.2.7 'Let thrower be equivalent to a function that throws _reason_.'

**Comment by ljharb** [comment]
Thanks, great catch!
