### ISSUE TITLE
Invoking "Call" in ThenFinally/CatchFinally

### ISSUE THREAD

**Issue by evilpie** [tc39/proposal-promise-finally#42]
I am going over the patch from @anba for the Firefox implementation. He made this comment:

> // Step 3.
> // FIXME: spec issue - Call() requires thisValue argument.

And indeed https://tc39.github.io/ecma262/#sec-call requires two arguments. AFAIK Abstraction operations in the ECMAScript Spec language don't allow you to not pass required arguments.

**Comment by ljharb** [comment]
Thanks, I'll update it to pass `undefined`.
