### ISSUE TITLE
[Bug] About test case returns a rejected-after-a-second promise

### ISSUE THREAD

**Issue by JiaLiPassion** [tc39/proposal-promise-finally#45]
I have a question about the behavior in this test case.

```javascript
describe('returns a rejected-after-a-second promise', () => {
    specify('from resolved', (done) => {
      adapter.resolved(3)
          .then((x) => {
            assert.strictEqual(x, 3);
            return x;
          })
          .finally(function onFinally() {
            assert(arguments.length === 0);
            setTimeout(done, 1.5e3);
            return new P((resolve, reject) => {
              setTimeout(() => reject(4), 1e3);
            });
          })
          .then(
              function onFulfilled(x) {
                assert.strictEqual(x, 3);
              },
              function onRejected() {
                throw new Error('should not be called');
              });
    });
```

`onFinally` return a `promise` which will reject after `1s`, but by the case here, the `then.onFulfilled` should be called, in my understanding, the `then.onRejected` should be called.
I have run the test and confirm current behavior is not correct, the `onReject` was called, but `mocha` doesn't fail because `promise.uncaughtReject` was not registered.

I have made a PR, #46  to fix this one, please check it, thank you!

**Comment by ljharb** [comment]
Wow, thanks - turns out all those tests weren't quite right due to not returning the promise to mocha *nor* calling the `done` callback at the appropriate times.

The test you're calling out does indeed have a bug; I'll rebase your PR on top of my commit that fixes all the tests :-)
